# Generated by Django 4.2.5 on 2023-10-26 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_code_alter_product_name'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='type',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='StockItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('qty', models.FloatField(default=0)),
                ('unit_price', models.CharField(max_length=12)),
                ('unit_selling_price', models.CharField(max_length=12)),
                ('unit_estmated_profit', models.CharField(max_length=12)),
                ('total_estmated_profit', models.CharField(max_length=12)),
                ('total_selling_price', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('1', 'in-stock'), ('2', 'out-stock')], default=1, max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stock')),
            ],
        ),
    ]
