# Generated by Django 4.2.5 on 2023-10-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_stockitems_stockitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='product',
            new_name='stock',
        ),
    ]
