# Generated by Django 4.2.5 on 2023-10-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_rename_product_stockitem_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='name',
            new_name='product',
        ),
    ]
