# Generated by Django 4.2.5 on 2023-10-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_rename_name_stockitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='total_estmated_profit',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='total_selling_price',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
