# Generated by Django 4.2.5 on 2023-10-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'CLIENT'), ('NORMAL_USER', 'NORMAL_USER'), ('ADMIN', 'ADMIN')], default='CLIENT', max_length=20),
        ),
    ]
